apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: workflows-sample
  name: workflows-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: workflows-sample
  template:
    metadata:
      labels:
        run: workflows-sample
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dwf-app"
        dapr.io/app-port: "5064"
        dapr.io/enable-api-logging: "true"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
    spec:
      containers:
        - name: workflows-sample
          image: mcr.microsoft.com/daprio/samples/dotnet-workflows:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5064
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
